# Generated by Django 5.1.1 on 2024-10-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='price_tag',
            field=models.CharField(default='Unknown-?€', max_length=10),
        ),
    ]
